# Generated by Django 5.1.7 on 2025-05-26 05:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_range', models.CharField(choices=[('morning', 'Morning (6AM-12PM)'), ('afternoon', 'Afternoon (12PM-5PM)'), ('evening', 'Evening (5PM-10PM)')], max_length=10)),
                ('time_block', models.CharField(max_length=50)),
                ('is_priority', models.BooleanField(default=False)),
                ('task_title', models.CharField(max_length=250)),
                ('type_of_type', models.CharField(max_length=50)),
                ('specific_time', models.TimeField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived'), ('Deleted', 'Deleted')], max_length=50)),
                ('is_recurring', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_priority', 'date', 'specific_time'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_priority', models.BooleanField(default=False)),
                ('task_title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived'), ('Deleted', 'Deleted')], max_length=50)),
                ('type_of_task', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('leisure', 'Leisure')], max_length=50)),
                ('week_start_date', models.DateField(default=django.utils.timezone.now)),
                ('week_end_date', models.DateField()),
                ('time_range', models.CharField(choices=[('morning', 'Morning (6AM-12PM)'), ('afternoon', 'Afternoon (12PM-5PM)'), ('evening', 'Evening (5PM-10PM)')], max_length=10)),
                ('time_block', models.CharField(max_length=50)),
                ('specific_time', models.TimeField()),
                ('is_recurring', models.CharField(choices=[('one_time', 'One Time'), ('recurring', 'Recurring')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
